const express = require('express');
const path = require('path');
const cors = require('cors');
const helmet = require('helmet');
const morgan = require('morgan');
require('dotenv').config();

const app = express();
const PORT = process.env.PORT || 3000;

// Middleware
app.use(helmet({
  contentSecurityPolicy: false, // Disabled for simple configuration with embeds/images
}));
app.use(cors());
app.use(morgan('combined'));
app.use(express.json());

// API Health Check
app.get('/api/health', (req, res) => {
  res.json({ status: 'ok', timestamp: new Date() });
});

// API Placeholders (Most logic is handled via Supabase Client + RLS, 
// but this exists for server-side admin tasks if needed later)
app.post('/api/admin/invite', (req, res) => {
  // Logic to send custom emails would go here
  res.json({ message: 'Invite sent (simulation)' });
});

// Serve Static Frontend (Production)
// Points to the client/dist folder generated by Vite
const distPath = path.join(__dirname, '../client/dist');
app.use(express.static(distPath));

// Fallback for SPA Routing
app.get('*', (req, res) => {
  res.sendFile(path.join(distPath, 'index.html'));
});

// Error Handling
app.use((err, req, res, next) => {
  console.error(err.stack);
  res.status(500).json({ error: 'Internal Server Error' });
});

app.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
});